blank_issues_enabled: false

contact_links:
  - name: Project Discussion
    url: https://github.com/pointfreeco/swift-perception/discussions
    about: Perception Q&A, ideas, and more
  - name: Documentation
    url: https://pointfreeco.github.io/swift-perception/main/documentation/perception/
    about: Read Perception's documentation
  - name: Videos
    url: https://www.pointfree.co/
    about: Watch videos to get a behind-the-scenes look at how this library and others were motivated and built
  - name: Slack
    url: https://www.pointfree.co/slack-invite
    about: Community chat
